// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Mongo DB
  //schema: "prisma/mongo.prisma",

  // Postgres
  schema: "prisma/postgres.prisma",

  migrations: {
    path: "prisma/migrations",
  },
  datasource: {

    // Mongo DB
    //url: process.env["DATABASE_URL_MONGO"],

    // Postgres
    url: process.env["DATABASE_URL_POSTGRES"],
  },
});


// npx prisma studio -> Rodar interface do banco de dados